version: "3"
services:

  node:
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - yarn
      - start

  mock-api:
    image: node
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - yarn
      - start-mockapi
