version: "3"
services:

  node:
    image: node
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://mock-api:3001
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - yarn
      - start

  mock-api:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    command:
      - yarn
      - start-mockapi
